version: '3'

services:
  redis:
    container_name: test-gobarber-db-redis
    image: redis:alpine
    ports:
      - '6379:6379'
  mongo:
    container_name: test-gobarber-db-mongo
    image: mongo
    ports:
      - '27017:27017'
volumes:
  postgres_data:
