name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Install Node v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Yarn
      run: |
        npm i -g yarn
    - name: Install dependencies
      run: |
        yarn
    - name: Setting up environment
      run: |
        cp .env.example .env
    - name: Runnning tests
      run: |
        yarn test
      env:
        CI: true
